# Generated by Django 5.2.1 on 2025-07-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
    ]
