# Generated by Django 5.2.1 on 2025-07-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
    ]
