# Generated by Django 5.2.1 on 2025-07-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_assignment_assignment_file'),
        ('course_class', '0010_course_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rubric',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course_class.course'),
        ),
    ]
