# Generated by Django 5.0.6 on 2025-07-23 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_assignment_assignment_file'),
        ('course_class', '0011_course_end_date_course_schedule_type_course_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rubric',
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course_class.course'),
        ),
    ]
