# Generated by Django 5.2.1 on 2025-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_remove_assignment_rubric_alter_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
