# Generated by Django 5.0.6 on 2025-07-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0008_notematerial_pdfmaterial_presentationmaterial_and_more'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_class.course'),
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TempCourse',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='assignments_completed',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='quizzes_completed',
        ),
    ]
