# Generated by Django 5.0.6 on 2025-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='video_duration',
            field=models.FloatField(default=0),
        ),
    ]
