# Generated by Django 5.0.6 on 2025-07-07 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0008_notematerial_pdfmaterial_presentationmaterial_and_more'),
        ('progress', '0002_alter_progress_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progress'},
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='progress',
            name='percentage_completed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'course')},
        ),
    ]
