# Generated by Django 5.0.6 on 2025-07-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0008_notematerial_pdfmaterial_presentationmaterial_and_more'),
        ('progress', '0003_alter_progress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='course_class.course'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
