# Generated by Django 5.2 on 2025-05-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='opt',
            new_name='otp',
        ),
    ]
