# Generated by Django 5.2 on 2025-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Instructor'), (3, 'Admin')], default=1),
        ),
    ]
