# Generated by Django 5.2 on 2025-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Student'), (2, 'Instructor'), (3, 'Admin')], max_length=20),
        ),
    ]
