# Generated by Django 5.2.1 on 2025-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prerequisites', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
