# Generated by Django 5.2.1 on 2025-05-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0002_rename_category_course_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Istructor',
            new_name='Instructor',
        ),
    ]
