# Generated by Django 5.2.1 on 2025-05-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0003_rename_istructor_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Course_Description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Instructor',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Title',
            new_name='title',
        ),
    ]
