# Generated by Django 5.1.5 on 2025-06-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0004_rename_category_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_materials/')),
                ('type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('presentation', 'Presentation'), ('notes', 'Notes')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course_class.course')),
            ],
        ),
    ]
