# Generated by Django 5.2.1 on 2025-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0005_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.CharField(max_length=255),
        ),
    ]
