# Generated by Django 5.2.1 on 2025-06-01 14:53

import course_class.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0006_alter_coursematerial_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='course_materials/', validators=[course_class.models.validate_material_file]),
        ),
    ]
