# Generated by Django 5.2.1 on 2025-06-13 06:29

import course_class.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0007_alter_coursematerial_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_materials/notes/', validators=[course_class.models.validate_material_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_materials/pdfs/', validators=[course_class.models.validate_material_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_materials/presentations/', validators=[course_class.models.validate_material_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_materials/videos/', validators=[course_class.models.validate_material_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
