# Generated by Django 5.2.4 on 2025-07-10 07:18

import course_class.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0008_notematerial_pdfmaterial_presentationmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_materials/', validators=[course_class.models.validate_material_file])),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('presentation', 'Presentation'), ('note', 'Note')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course_class.course')),
            ],
        ),
        migrations.DeleteModel(
            name='NoteMaterial',
        ),
        migrations.DeleteModel(
            name='PDFMaterial',
        ),
        migrations.DeleteModel(
            name='PresentationMaterial',
        ),
        migrations.DeleteModel(
            name='VideoMaterial',
        ),
    ]
