# Generated by Django 5.2.4 on 2025-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0009_coursematerial_delete_notematerial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
