# Generated by Django 5.2.1 on 2025-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_class', '0010_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Live', 'Live'), ('Self-paced', 'Self-paced')], default='Self-paced', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
